env:
  global:
    - CC_TEST_REPORTER_ID=949a899ebc27cda5cd650c0247537ab4b815f1aa7d1e1b4f098fe430de7379f0
language: node_js
node_js:
  - 8.11.2
notifications:
  email: false
before_script:
  - npm install -g codeclimate-test-reporter
  - npm install -g coveralls
  - npm install -g sequelize
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run build
  - npm run coveralls
  - codeclimate-test-reporter < coverage/lcov.info
  - coveralls < coverage/lcov.info